Js/logic create
RollingFit-Grupo/RollingFit pull request #10
Opened 2023-05-13 23:05 UTC by MauricioSor

Listo la logica de create js.

2023-05-14 21:18 UTC, mjcorrea404 commented on js/administracion.js
> +function crearServicio() {
Aquí esta faltando la función para que se cierre el modal (en el editar modal se cierra correctamente)

2023-05-16 18:33 UTC, LucianoAngeleri requested changes
Todos los servicios de muestra se cargan y se renderizan correctamente, con los mensajes de validaciones correspondientes.
El Delete funciona correctamente.
En la parte de Create y Update:
* Revisar las validaciones de URL imágenes.
* Revisar la descripción de los servicios de muestra

2023-05-16 18:33 UTC, LucianoAngeleri commented on js/administracion.js
> +    `Una rutina de spinning es una actividad de entrenamiento en bicicleta estática que se realiza en grupo, guiada por un instructor. Esta disciplina combina música enérgica, cambios de ritmo y resi
Revisar que las descripciones en los servicios de muestra , deben cumplir con las validaciones, en las pruebas de modificación al querer guardarlas, no se valida en esos campos

2023-05-16 18:33 UTC, LucianoAngeleri commented on js/administracion.js
> +  Swal.fire(
Pueden utilizar los modales de modalSuccess, que contiene los estilos para mensajes de éxito (se encuentran en la parte de borrar). `modalSuccess.fire{ }`

2023-05-17 04:03 UTC, LucianoAngeleri approved these changes

2023-05-17 04:45 UTC, maxivega0 approved these changes
Correcciones de las observaciones, logica bien aplicada. Codigo limpio!

2023-05-17 04:46 UTC, merged